name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make all
    - name: 'Upload Build'
      uses: actions/upload-artifact@v4
      with:
        name: os
        path: template-x86_64.iso
        retention-days: 3
